### ISSUE TITLE
Valorant Support

### ISSUE THREAD

**Issue by soupbird** [AntiMicroX/antimicrox-profiles#14]
So i used to use ReWasd to play valorant (fps that doesn't support gamepads) and when you launch the application it only allows you to use one input to like do everything for example if you were to plug in a gamepad and a mouse you cant use both at the same time it would only allow you to use one. And that's the issue, i've tried unplugging my mouse and relaunching the game, only navigating the client with my gamepad but it still didn't let me use my gamepad after i actually launched the game, thanks.

**Comment by pktiuk** [comment]
Valorant doesn't and won't work with antimicrox. Linked issue: https://github.com/AntiMicroX/antimicrox/issues/406

This is caused by an aggressive anticheat used in this game https://www.sp-cy.com/article/is-valorants-anticheat-spyware/
